### ISSUE TITLE
Schema 

### ISSUE THREAD

**Issue by AdamYLiang** [taeinha/VidTube#1]
**Likes**
- [x] Likes should be a polymorphic association since you can like both comments and videos. That way you can keep track of a `likable_id` instead of `video_id` and `comment_id`. 

**Comments**
- [x] No need to store `reply_ids` since we can just grab that with a query 

Let me know if you have any questions about these changes!

**Comment by taeinha** [comment]
- Created a polymorphic association for `likes`, so that it can be referenced to either videos or comments. I changed `:like_type` to `:is_like` boolean since it was named similarly to `:likable_type`.

- Removed `reply_ids` from comments table
