### ISSUE TITLE
Sample State 

### ISSUE THREAD

**Issue by AdamYLiang** [taeinha/VidTube#2]
- [x] Only user `1` should have `uploaded_videos` in state since they are logged in. We only care about this information for the logged in user. 
- [x] No need for `likes` slice of state, we can query for the amount of likes in the backend and pass that up as a key for each video and comment. 

Let me know if you have any questions about these changes!

**Comment by taeinha** [comment]
- Changed users slice of state so that only logged in user `1` has `uploaded_videos`

- Removed `likes` slice of state, and added `like_counts` as a key for each videos and comments
