### ISSUE TITLE
Frontend/Backend Routes

### ISSUE THREAD

**Issue by AdamYLiang** [taeinha/VidTube#3]
**Frontend**
- [x] Should have a search results rout 

**Backend**
- [x] Should have `POST`/`DELETE` routes for comment likes as well.
- [x] One of our `likes` routes seems to have a typo/undefined resource in it. 
- [x] Comments `PATCH`/`DELETE` do not need access to the video, just looking up by ID will work.

Let me know if you have any questions about these changes!

**Comment by taeinha** [comment]
- Added `results` route for frontend that renders `VideoIndex` and `VideoIndexItem` based on search query

- Added `comment_likes` in backend, separated from `video_likes`. Should both `comment_likes` and `video_likes` be in one controller `likes` with 2 `POST` and 2 `DELETE` actions?

- Updated comments `PATCH` / `DELETE` routes to only search by comment's `id`
