### ISSUE TITLE
MVP User Auth review

### ISSUE THREAD

**Issue by taeinha** [taeinha/VidTube#5]
Completed User Auth MVP
- Fully functional User Auth, with bootstrapping the current user and rendering specific errors

- Almost pixel perfect in terms of styling

- Created Nav Bar with a dropdown when the user profile is clicked on

**Comment by AdamYLiang** [comment]
Hey Tae, it looks great! Just a couple of fixes: 

- [ ] Consider having `VidTube` logo on `signup/login` to route back to main site. This is not a feature of the original app but could be helpful for people navigating the site. 
- [ ] Dropdown menu should appear underneath the user profile bubble. 
- [ ] Move `VidTube` logo a bit more to the right. Usually the sidebar would be there but we can adjust for it now. 
- [ ] `login/signup` should have a Protected route. I should not able to access `login` if the user is already logged in. 

Let me know if you have any issues with these fixes!

**Comment by taeinha** [comment]
Hi Adam, I made updates to reflect these changes and deployed them to heroku.

**Comment by AdamYLiang** [comment]
Nice work!
